# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d6266bfb178317529b3e57f2e6dc849522f39f4a052b14462a49c72d19166b37ce853ee21626813232024c314564043a1e0db80851d08ebec6a9b7a252290a1

test:
  secret_key_base: 05854e9e5f9e77c329bcfeebc6f8551b6601e0496a69744670cb601e4a1e484a1299208c9c6fbf9b2041e9dc970283b802ed4e0d721ef055e5a6658bd0a2fa85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
